### ISSUE TITLE
Allow customers to choose their own billing details

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-templates#287]
There are a lot of requests from EU customers to change their billing address/details. We are using quaderno right now to send these invoices, but since Stripe now allows us to send invoices directly I think we should just migrate all the data that we have from quaderno to Stripe and then just send invoices from Stripe only.

**Comment by xarg** [comment]
Example ticket: https://gorgias.gorgias.io/app/ticket/23370356

**Comment by ghinda** [comment]
Billing information can now be updated from the Dashboard (in `Settings > Subscriptions`).
